datastore:
    image: mongo
    ports:
        - "27017:27017"
frontend:
    build: .
    command: python -u app/app.py
    ports:
    - "5000:5000"
    volumes:
    - .:/app
    links:
        - datastore